In [3]:
# Вариант 1
# A = | 1   2   4 |
#     | 7   5  -2 |
#     | -2  1   3 |

# B = |-1   0   3 |
#     | 2  -6   1 |
#     |-7   1   5 |

# C = |-2   3 |
#     | 4   0 |
#     |7   -1 |

# A + B = | 1+(-1)   2+0     4+3  | = | 0   2   7 |
#         | 7+2      5+(-6) -2+1 |   | 9  -1  -1 |
#         |-2+(-7)   1+1     3+5 |   |-9   2   8 |

# B - A = |-1-1   0-2    3-4  | = |-2  -2  -1 |
#         | 2-7  -6-5    1-(-2)|   |-5 -11   3 |
#         |-7-(-2) 1-1   5-3  |   |-5   0   2 |

# A * C: 3x3 * 3x2 = 3x2

# 1.1 = 1*(-2) + 2*4 + 4*7 = -2 + 8 + 28 = 34
# 1.2 = 7*(-2) + 5*4 + (-2)*7 = -14 + 20 -14 = -8
# 1.3 = -2*(-2) + 1*4 + 3*7 = 4 + 4 + 21 = 29

# 2.1 = 1*3 + 2*0 + 4*(-1) = 3 + 0 - 4 = -1
# 2.2 = 7*3 + 5*0 + (-2)*(-1) = 21 + 0 + 2 = 23
# 2.3 = -2*3 + 1*0 + 3*(-1) = -6 + 0 -3 = -9

# A * C = |34  -1|
#         |-8  23|
#         |29  -9|

# A * B * C:

# A * B: 3×3 * 3×3 = 3×3

# 1.1 = 1*(-1) + 2*2 + 4*(-7) = -1 + 4 - 28 = -25
# 1.2 = 1*0 + 2*(-6) + 4*1 = 0 -12 + 4 = -8
# 1.3 = 1*3 + 2*1 + 4*5 = 3 + 2 + 20 = 25

# 2.1 = 7*(-1) + 5*2 + (-2)*(-7) = -7 + 10 + 14 = 17
# 2.2 = 7*0 + 5*(-6) + (-2)*1 = 0 -30 -2 = -32
# 2.3 = 7*3 + 5*1 + (-2)*5 = 21 + 5 -10 = 16

# 3.1 = -2*(-1) + 1*2 + 3*(-7) = 2 + 2 -21 = -17
# 3.2 = -2*0 + 1*(-6) + 3*1 = 0 -6 + 3 = -3
# 3.3 = -2*3 + 1*1 + 3*5 = -6 + 1 + 15 = 10

# A * B = |-25  -8  25|
#         |17 -32  16 |
#         |-17 -3  10 |

# (A * B) * C: 3×3 * 3×2 = 3×2

# 1.1 = -25*(-2) + (-8)*4 + 25*7 = 50 -32 + 175 = 193
# 1.2 = 17*(-2) + (-32)*4 + 16*7 = -34 -128 + 112 = -50
# 1.3 = -17*(-2) + (-3)*4 + 10*7 = 34 -12 + 70 = 92

# 2.1 = -25*3 + (-8)*0 + 25*(-1) = -75 + 0 -25 = -100
# 2.2 = 17*3 + (-32)*0 + 16*(-1) = 51 + 0 -16 = 35
# 2.3 = -17*3 + (-3)*0 + 10*(-1) = -51 + 0 -10 = -61

# A * B * C = |193 -100|
#             |-50   35|
#             |92  -61 |

In [6]:
# Вариант 2
# A = | 0   3   4 |
#     |-7   1  -2 |
#     | 2  -1   3 |

# B = | 1   2   4 |
#     | 7   0  -2 |
#     |-3  -2   5 |

# C = |-3   2 |
#     | 0   4 |
#     |-1   7 |

# A + B = | 0+1     3+2     4+4  | = | 1   5   8 |
#         |-7+7     1+0    -2+(-2)|   | 0   1  -4 |
#         | 2+(-3) -1+(-2)  3+5  |   |-1  -3   8 |

# B - A = | 1-0     2-3     4-4  | = | 1  -1   0 |
#         | 7-(-7)  0-1    -2-(-2)|   |14  -1   0 |
#         |-3-2    -2-(-1)  5-3  |   |-5  -1   2 |

# A * C: 3x3 * 3x2 = 3x2

# 1.1 = 0*(-3) + 3*0 + 4*(-1) = 0 + 0 - 4 = -4
# 1.2 = -7*(-3) + 1*0 + (-2)*(-1) = 21 + 0 + 2 = 23
# 1.3 = 2*(-3) + (-1)*0 + 3*(-1) = -6 + 0 - 3 = -9

# 2.1 = 0*2 + 3*4 + 4*7 = 0 + 12 + 28 = 40
# 2.2 = -7*2 + 1*4 + (-2)*7 = -14 + 4 - 14 = -24
# 2.3 = 2*2 + (-1)*4 + 3*7 = 4 - 4 + 21 = 21

# A * C = |-4  40|
#         |23 -24|
#         |-9  21|

# A * B * C:

# A * B: 3×3 * 3×3 = 3×3

# 1.1 = 0*1 + 3*7 + 4*(-3) = 0 + 21 - 12 = 9
# 1.2 = 0*2 + 3*0 + 4*(-2) = 0 + 0 - 8 = -8
# 1.3 = 0*4 + 3*(-2) + 4*5 = 0 -6 + 20 = 14

# 2.1 = -7*1 + 1*7 + (-2)*(-3) = -7 + 7 + 6 = 6
# 2.2 = -7*2 + 1*0 + (-2)*(-2) = -14 + 0 + 4 = -10
# 2.3 = -7*4 + 1*(-2) + (-2)*5 = -28 -2 -10 = -40

# 3.1 = 2*1 + (-1)*7 + 3*(-3) = 2 -7 -9 = -14
# 3.2 = 2*2 + (-1)*0 + 3*(-2) = 4 + 0 -6 = -2
# 3.3 = 2*4 + (-1)*(-2) + 3*5 = 8 + 2 + 15 = 25

# A * B = | 9  -8  14|
#         | 6 -10 -40|
#         |-14 -2  25|

# (A * B) * C: 3×3 * 3×2 = 3×2

# 1.1 = 9*(-3) + (-8)*0 + 14*(-1) = -27 + 0 -14 = -41
# 1.2 = 6*(-3) + (-10)*0 + (-40)*(-1) = -18 + 0 + 40 = 22
# 1.3 = -14*(-3) + (-2)*0 + 25*(-1) = 42 + 0 -25 = 17

# 2.1 = 9*2 + (-8)*4 + 14*7 = 18 -32 + 98 = 84
# 2.2 = 6*2 + (-10)*4 + (-40)*7 = 12 -40 -280 = -308
# 2.3 = -14*2 + (-2)*4 + 25*7 = -28 -8 + 175 = 139

# A * B * C = |-41   84|
#             | 22 -308|
#             | 17  139|

In [7]:
# Вариант 3
# A = | 5   2   9 |
#     | 7   0  -2 |
#     |-2   1   6 |

# B = | 1  -2   1 |
#     | 7   5  -2 |
#     |-2   8   3 |

# C = |-2   3 |
#     | 4   5 |
#     | 0  -1 |

# A + B = | 5+1     2+(-2)   9+1  | = | 6   0  10 |
#         | 7+7     0+5     -2+(-2)|   |14   5  -4 |
#         |-2+(-2)  1+8      6+3  |   |-4   9   9 |

# B - A = | 1-5    -2-2     1-9  | = |-4  -4  -8 |
#         | 7-7     5-0    -2-(-2)|   | 0   5   0 |
#         |-2-(-2)  8-1     3-6  |   | 0   7  -3 |

# A * C: 3x3 * 3x2 = 3x2

# 1.1 = 5*(-2) + 2*4 + 9*0 = -10 + 8 + 0 = -2
# 1.2 = 7*(-2) + 0*4 + (-2)*0 = -14 + 0 + 0 = -14
# 1.3 = -2*(-2) + 1*4 + 6*0 = 4 + 4 + 0 = 8

# 2.1 = 5*3 + 2*5 + 9*(-1) = 15 + 10 - 9 = 16
# 2.2 = 7*3 + 0*5 + (-2)*(-1) = 21 + 0 + 2 = 23
# 2.3 = -2*3 + 1*5 + 6*(-1) = -6 + 5 - 6 = -7

# A * C = |-2  16|
#         |-14 23|
#         | 8  -7|

# A * B * C:

# A * B: 3×3 * 3×3 = 3×3

# 1.1 = 5*1 + 2*7 + 9*(-2) = 5 + 14 - 18 = 1
# 1.2 = 5*(-2) + 2*5 + 9*8 = -10 + 10 + 72 = 72
# 1.3 = 5*1 + 2*(-2) + 9*3 = 5 - 4 + 27 = 28

# 2.1 = 7*1 + 0*7 + (-2)*(-2) = 7 + 0 + 4 = 11
# 2.2 = 7*(-2) + 0*5 + (-2)*8 = -14 + 0 - 16 = -30
# 2.3 = 7*1 + 0*(-2) + (-2)*3 = 7 + 0 - 6 = 1

# 3.1 = -2*1 + 1*7 + 6*(-2) = -2 + 7 - 12 = -7
# 3.2 = -2*(-2) + 1*5 + 6*8 = 4 + 5 + 48 = 57
# 3.3 = -2*1 + 1*(-2) + 6*3 = -2 - 2 + 18 = 14

# A * B = | 1  72  28|
#         |11 -30   1|
#         |-7  57  14|

# (A * B) * C: 3×3 * 3×2 = 3×2

# 1.1 = 1*(-2) + 72*4 + 28*0 = -2 + 288 + 0 = 286
# 1.2 = 11*(-2) + (-30)*4 + 1*0 = -22 -120 + 0 = -142
# 1.3 = -7*(-2) + 57*4 + 14*0 = 14 + 228 + 0 = 242

# 2.1 = 1*3 + 72*5 + 28*(-1) = 3 + 360 - 28 = 335
# 2.2 = 11*3 + (-30)*5 + 1*(-1) = 33 -150 -1 = -118
# 2.3 = -7*3 + 57*5 + 14*(-1) = -21 + 285 -14 = 250

# A * B * C = |286  335|
#             |-142 -118|
#             |242  250|

In [8]:
import numpy as np

A4 = np.array([[1, -2, 8],
               [7, 5, -2],
               [-2, 3, 0]])

B4 = np.array([[0, 2, 4],
               [1, -3, -2],
               [-2, 1, 3]])

C4 = np.array([[0, 3],
               [5, -4],
               [7, -1]])

print("=== Вариант 4 ===")
print("A + B:\n", A4 + B4)
print("\nB - A:\n", B4 - A4)
print("\nA @ C:\n", A4 @ C4)
print("\nA @ B @ C:\n", A4 @ B4 @ C4)

=== Вариант 4 ===
A + B:
 [[ 1  0 12]
 [ 8  2 -4]
 [-4  4  3]]

B - A:
 [[-1  4 -4]
 [-6 -8  0]
 [ 0 -2  3]]

A @ C:
 [[ 46   3]
 [ 11   3]
 [ 15 -18]]

A @ B @ C:
 [[ 304 -150]
 [  69   27]
 [-163   75]]


In [9]:
import numpy as np

A5 = np.array([[9, 2, 4],
               [7, 5, -5],
               [6, -2, 3]])

B5 = np.array([[8, 2, 4],
               [0, 1, -3],
               [-2, 1, 6]])

C5 = np.array([[-2, 0],
               [4, 8],
               [1, -1]])

print("=== Вариант 5 ===")
print("A + B:\n", A5 + B5)
print("\nB - A:\n", B5 - A5)
print("\nA @ C:\n", A5 @ C5)
print("\nA @ B @ C:\n", A5 @ B5 @ C5)

=== Вариант 5 ===
A + B:
 [[17  4  8]
 [ 7  6 -8]
 [ 4 -1  9]]

B - A:
 [[-1  0  0]
 [-7 -4  2]
 [-8  3  3]]

A @ C:
 [[ -6  12]
 [  1  45]
 [-17 -19]]

A @ B @ C:
 [[ 22 138]
 [-93 129]
 [ 16  56]]


In [10]:
# 1. Из 1000 собранных на заводе телевизоров 5 штук бракованных.
# Эксперт проверяет один наугад выбранный телевизор из этой
# 1000. Найдите вероятность того, что проверяемый телевизор
# окажется бракованным.

# 5/1000 = 0,005

In [19]:
# 2. В урне 9 красных, 6 жёлтых и 5 зелёных шаров. Из урны наугад
# достают один шар. Какова вероятность того, что этот шар
# окажется жёлтым?

# 6/20 = 3/10 = 0,3

In [13]:
# 3. В чемпионате мира участвуют 16 команд. С помощью жребия
# их нужно разделить на четыре группы по четыре команды в
# каждой. В ящике вперемешку лежат карточки с номерами групп:
# 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4. Капитаны команд тянут по
# одной карточке. Какова вероятность того, что команда
# Португалии окажется во второй группе?

# 4/16 = 1/4 = 0,25

In [21]:
# 4. В группе туристов 8 человек. С помощью жребия они
# выбирают шестерых человек, которые должны идти в село в
# магазин за продуктами. Какова вероятность того, что турист Д.,
# входящий в состав группы, пойдёт в магазин?

# Логика
# 1-2/8 = 6/8 = 3/4 = 0,75

# Комбинаторика
# 21/28 = 3/4 = 0,75

In [16]:
# 5. В чемпионате по футболу участвуют 16 команд, которые
# жеребьевкой распределяются на 4 группы: A, B, C и D. Какова
# вероятность того, что команда Англии не попадает в группу A?

# 1 команда, 4 случая - вероятность 0,75

In [20]:
# 6. В классе 21 учащийся, среди них две подруги - Аня и Нина.
# Класс случайным образом делят на семь групп, по 3 человека в
# каждой. Найдите вероятность того, что Аня и Нина окажутся в
# одной группе.

# 2/20 = 1/10 = 0,1

In [22]:
# 7. Механические часы с двенадцатичасовым циферблатом в
# какой-то момент сломались и перестали идти. Найдите
# вероятность того, что часовая стрелка остановилась, достигнув
# отметки 7, но не дойдя до отметки 1.

# 6/12 = 1/2 = 0,5

In [23]:
# 8. Механические часы с двенадцатичасовым циферблатом в
# какой-то момент сломались и перестали ходить. Найдите
# вероятность того, что часовая стрелка застыла, достигнув
# отметки 6, но не дойдя до отметки 9 часов.

# 3/12 = 1/4 = 0,25

In [24]:
# 9. В случайном эксперименте симметричную монету бросают 2
# раза. Найдите вероятность того, что орел выпадет ровно 1 раз.

# 2/4 = 1/2 = 0,5

In [26]:
# 10. В случайном эксперименте симметричную монету бросают
# дважды. Найдите вероятность того, что орёл не выпадет ни разу.

# 1/4 = 0,25

In [27]:
# 11. Вероятность того, что новая шариковая ручка пишет плохо
# (или не пишет), равна 0,19. Покупатель в магазине выбирает одну
# такую ручку. Найдите вероятность того, что эта ручка пишет
# хорошо.

# 1-0,19 = 0,81

In [28]:
# 12. При изготовлении подшипников диаметром 67 мм
# вероятность того, что диаметр будет отличаться от заданного не
# больше, чем на 0,01 мм, равна 0,965. Найдите вероятность того,
# что случайный подшипник будет иметь диаметр меньше чем
# 66,99 мм или больше чем 67,01 мм.

# 1 - 0,965 = 0,035

In [29]:
# 13. На экзамене по геометрии школьнику достаётся одна задача из
# сборника. Вероятность того, что эта задача по теме «Углы», равна
# 0,1. Вероятность того, что это окажется задача по теме
# «Параллелограмм», равна 0,6. В сборнике нет задач, которые
# одновременно относятся к этим двум темам. Найдите вероятность
# того, что на экзамене школьнику достанется задача по одной из
# этих двух тем.

# 0,1 + 0,6 = 0,7